### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/common/collect/AbstractIterator

### ISSUE THREAD

**Issue by tyler-whitman** [pusher/pusher-websocket-android#10]
I am getting java.lang.NoClassDefFoundError: com/google/common/collect/AbstractIterator when including com.pusher:pusher-websocket-android:0.2.1 in my project.

If I add the AbstractIterator class via the google collections library, then I face java.lang.NoSuchMethodError: com.google.common.collect.Multimaps.filterKeys because of an introduced dependency from the google collections library.

Any ideas?

Thanks,
Tyler

**Comment by tyler-whitman** [comment]
I figured out the problem, looks like a dependency is using a old Guava version. Below is how I fixed it.

compile 'com.google.guava:guava:19.0'
compile ('com.pusher:pusher-websocket-android:0.2.1') {
    exclude(group: 'com.google.guava', module: 'guava')
}

**Comment by luismfonseca** [comment]
Ok then, closing the issue!
