### ISSUE TITLE
Please remove guava

### ISSUE THREAD

**Issue by carlonzo** [pusher/pusher-websocket-android#16]
I dont want to add guava to the list of dependencies. guava-retrying is adding guava and findbugs. Can you please avoid using it?

**Comment by Rhysjc** [comment]
I second this, Guava is adding almost 15k methods to my project, and has forced me to turn on multidex.

**Comment by zmarkan** [comment]
I've taken Guava out - will be sorted in the next release: 
https://github.com/pusher/pusher-websocket-android/pull/19

**Comment by Rhysjc** [comment]
Great news, thanks @zmarkan. Any news on when this release will be out?

**Comment by zmarkan** [comment]
Should be either tonight or early next week.

**Comment by zmarkan** [comment]
I just pushed to maven central, the version 0.4.0 of the lib should be available in a matter of hours.
