### ISSUE TITLE
Minimum SDK Version

### ISSUE THREAD

**Issue by DigNZ** [pusher/pusher-websocket-android#18]
Is it possible to use a lower minimum SDK version than 23?

The problem is that the rest of my app works all the way down to minimum SDK 9 but once pusher is incorporated then 23 is the minimum, this cuts out the majority of android users as there are significant numbers still using kitkat and lollipop but this minimum only allows the app to be installed on Marshmellow and Nougat.

**Comment by zmarkan** [comment]
Hi,

the library is already using a lower SDK version -  `minSdkVersion 9`. The only thing with minimum SDK version 23 was the Example - I lowered it to 9 as well now: https://github.com/pusher/pusher-websocket-android/pull/20
