### ISSUE TITLE
Getting 403 when try to connect to pusher

### ISSUE THREAD

**Issue by stepango** [pusher/pusher-websocket-android#26]
Here is en error i get when try to use pusher with FCM.
[token upload] Received status 403 with: {"token_validation_response":{"description":"Unauthorized","success":false,"platform":"fcm"}}

Is there any way to fix it?

**Comment by zeeshansuleman** [comment]
i got the same error for ios . have you fixed it for android? 

**Expected 2xx response to registration request; got 403 with response: {"token_validation_response":{"description":"Post https://api.development.push.apple.com/3/device/3C3C8EE187A49F76076331355990AA73483524F4CCC8A41E87FE7045EEBC87: remote error: tls: internal error","sent_device_token":"3C3C8EE187A49F76076331355990AA73483524F4CCC8A41E87FE70**

**Comment by aya-salama1989** [comment]
>  [token upload] Received status 403 with: {"token_validation_response":{"description":"Unauthorized","success":false,"platform":"fcm"}}
> 
>  java.lang.NullPointerException: Attempt to invoke interface method 'void com.pusher.android.notifications.interests.InterestSubscriptionChangeListener.onSubscriptionChangeFailed(int, java.lang.String)' on a null object reference


For me the solution was rechecking server key used from FCM into the pusher dash-board, as Firebase supported me with a different server key with notification that it would be more stable, No idea why :/

**Comment by zeeshansuleman** [comment]
hello dear , i have resolved the issue . it was due to the certificates i
was not genrerating it properly.

**Comment by lastsky** [comment]
confim too, it was due to expired certificates.

**Comment by JvZuidam** [comment]
I also happen to get this error and I tried recheking the  sercer key used from FCM into the pusher dashboard but I keep getting the same error. Also for some weird reason the key provided by Firebase is different from the key that's in my google-services.json

**Comment by zmarkan** [comment]
What do you mean by key provided by Firebase - the Server Key? 
That is a secret key that shouldn't be part of your `google-services.json`.

**Comment by kn100** [comment]
Closing due to age
