### ISSUE TITLE
Not intercepting push messages (GCM)

### ISSUE THREAD

**Issue by LaurieScheepers** [pusher/pusher-websocket-android#28]
After following all the steps in the guide to implement GCM, I can't get push messages to actually be intercepted. All callbacks work fine (GCM registration, subscription to an interest) but the onMessageReceived callback (in the GCMPushNotificationReceivedListener) is not called.

I get the following in the log when a push is delivered:

`E/FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.`

Any ideas about this?

My AndroidManifest file has the following receivers and services declared:

```
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="com.app.myapp" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.pusher.android.notifications.gcm.PusherGCMListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>

        <service
            android:name="com.pusher.android.notifications.gcm.GCMInstanceIDListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID"/>
            </intent-filter>
        </service>

        <service
            android:name="com.pusher.android.notifications.gcm.GCMRegistrationIntentService"
            android:exported="false">
        </service>

**Comment by zmarkan** [comment]
Is your app running in the foreground? 
The callback only triggers when the app is in the foreground - otherwise it goes in the notifications tray.

**Comment by LaurieScheepers** [comment]
Thanks, I realized that later. In the end I resorted to creating a
broadcast receiver and intercepting the GCM messages there.

Maybe you should update the documentation though, as my post is not the
first one mentioning this.

**Comment by zmarkan** [comment]
Ok, yep - will do. Thanks for the suggestion.
