### ISSUE TITLE
About Unsubscribe Chanels

### ISSUE THREAD

**Issue by mohan9** [pusher/pusher-websocket-android#30]
unsubscribe method is not working.

may be its incomplete.

**Comment by zmarkan** [comment]
Hi, is that from Push notifications interests or from Pusher Channels? 

Thanks

**Comment by mohan9** [comment]
Pusher Channel Unsubscribe not working.

**Comment by zmarkan** [comment]
Hmm - I'll look into it, thanks

**Comment by blastering66** [comment]
Yeah mee too... 

Apps Logged out, but still got notification..

Pls update the bug :(

**Comment by zmarkan** [comment]
@blastering66 are you talking about Push Notifications or Channels (Websocket realtime subscriptions). The OP meant channels and not push notifications.

**Comment by zmarkan** [comment]
@mohan9 I didn't see anything strange with the library. Can you share some code snippets? 

Or, even better if you could open a support ticket here and I can look into it for you: https://support.pusher.com/

Thanks!

**Comment by blastering66** [comment]
Mine the Push Notification, Unsubscribe Interest. and i have created a ticket just a momment ago.

(Android) In login, i subscribed user_token as Interest. Then, in Logout i unsubscribed interest using that user_token.

then i logging in with other account which generated a new user_token, then i subscribed it.

But i still got notifcation from previous user_token.

it seem, the unsubscribe didnt work. (at least in android, cuz my ios developer in ios push notification work fine)

**Comment by blastering66** [comment]
This is From Login

`PusherAndroid pusherAndroid = new PusherAndroid(BuildConfig.APP_KEY_PUSHER_STAGING);
        PushNotificationRegistration nativeReg = pusherAndroid.nativePusher();

            String subcribe_notif = spf.getString(GlobalVar.SPF_APP_AUTH, "");

            nativeReg.subscribe(subcribe_notif, new InterestSubscriptionChangeListener() {
                @Override
                public void onSubscriptionChangeSucceeded() {
                    Log.e("FCM MY JOB", "SUKSES");
                }

                @Override
                public void onSubscriptionChangeFailed(int statusCode, String response) {
                    Log.e(GlobalVar.LOG_INIT_TAG, "FAILED" + response);
                }
            });

            nativeReg.registerFCM(context, new PushNotificationRegistrationListener() {
                @Override
                public void onSuccessfulRegistration() {
                    Log.e("FCM", "SUKSES");
                }

                @Override
                public void onFailedRegistration(int statusCode, String response) {
                    Log.e(GlobalVar.LOG_INIT_TAG, "FAILED , " + response);
                }
            });`

And This is From Logout

`nativeReg.unsubscribe(spf.getString(GlobalVar.SPF_APP_AUTH, ""));
            pusherAndroid.unsubscribe(spf.getString(GlobalVar.SPF_APP_AUTH, ""));
            pusherAndroid.disconnect();`

**Comment by zmarkan** [comment]
Can you pass the `InterestSubscriptionChangeListener` to this call as well? Maybe it's failing for some reason. This should unsubscribe correctly.

Also - it's a long shot but still - any chance the shared prefs have been cleared when you unsubscribe? Can you check that `subscribe_notif` is the same string as the one before you call `nativeReg.unsubscribe`. 

Also - the last 2 lines, including `pusherAndroid.unsubscribe` call are not necessary in your case - that's only for Pusher's websocket subscription and not for push notifications.  ;)

Thanks

**Comment by blastering66** [comment]
I dont understand by u mean about passing the InterestSubscriptionChangeListener.....
But the variable from SharedPref is the same.

and by the way, I Change the Version of Pusher java client to 1.3.0   NOT The Newest Ones (1.4.0)

and it works fine (the unsubscribe interest). I didnt get the notification anymore

**Comment by kn100** [comment]
Closing due to age
