### ISSUE TITLE
FCMMessagingService needs to be fixed

### ISSUE THREAD

**Issue by YoonjaeYoo** [pusher/pusher-websocket-android#31]
To use FCM with pusher, I need to add two services to my manifest, 'com.pusher.android.notifications.fcm.FCMMessagingService' and 'com.pusher.android.notifications.fcm.FCMInstanceIDService'.

Problem arises in `FCMMessagingService`. Its `onMessageReceived` method is as below:
```
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        Log.d(TAG, "Received from FCM: " + remoteMessage);

        if (listener != null) {
            listener.onMessageReceived(remoteMessage);
        }
    }
```
and I can set listener with `setOnMessageReceivedListener`.
This is the only place I can set my code to handle `RemoteMessage`.
Fine.

But what if app was cleared from memory and listener is unset by system?
`listener` only lives in memory so my previous set listener will be ignored even if new message comes in.

It should be fixed such as follows:
1. Users can specify their own FirebaseMessagingService class.
2. `RemoteMessage` has to be handled in their own FIrebaseMessagingService, not by weakly referenced `listener`.

Thank you.

**Comment by zmarkan** [comment]
Thanks, I'll look into that.

**Comment by jsantacruz** [comment]
Running into the same issue, I thought I can just overwrite the FirebaseMessagingService but that doesn't seem to work (FCMMessagingService is not registered in your AndroidManifest.xml).

Would it be possible to specify our own service class?

**Comment by zmarkan** [comment]
Yes, I believe this is a good idea. I've put it on my TODO.

**Comment by zmarkan** [comment]
I've made the changes - this will allow anything extending the `FirebaseMessagingService` to be used instead of our `FCMMessagingService`.

The PR is here:  https://github.com/pusher/pusher-websocket-android/pull/36

I will merge it soon.

**Comment by zmarkan** [comment]
The change has been merged, will be released in a few days.
