### ISSUE TITLE
Every time I create a Pusher object, I need to specify app key

### ISSUE THREAD

**Issue by YoonjaeYoo** [pusher/pusher-websocket-android#33]
I need to type below every time I create a `PusherAndroid` object:
```
PusherAndroid pusher = new PusherAndroid("XXXXXXXXXXXXXX");
```

Rather than having to pass `String appKey` parameter to the constructor of `PusherAndroid`, what about passing `Context context`?
That is:
```
<!-- only once -->
<string name="pusher_app_key">XXXXXXXXXXXXX</string>

// every time
PusherAndroid pusher = new PusherAnroid(this);
```

Of course, `pusher_app_key` is a predefined key in your library, if you accept this feature.
It will eliminate a lot of boilerplate codes when there are many `PusherAndroid` objects. (ex: each Activity has its own PusherAndroid)

**Comment by zmarkan** [comment]
You could always create it centrally and inject it - using Dagger for example. I don't think we'd need to have a `Context` just for this.

**Comment by YoonjaeYoo** [comment]
@zmarkan I know that using Dagger would solve it but not everyone uses Dagger. `puser-websocket-android` should embrace any kind of Android developers, not just Dagger users, I think.
As you know, `Context` is an important and elemental object in Android platform. Many  famous libraries including Facebook SDK, Firebase, Glide take their first parameter of type `Context`.

And also, by extracting the app key into strings.xml file, developers can separate their development/production keys in different flavor, not like this:
```
PusherAndroid pusher = new PusherAndroid(BuildConfig.FLAVOR.equals("production") ? "XXXXXXXXXXX" : "YYYYYYYYYYY");
```
but like below:
```
PusherAndroid pusher = new PusherAndroid(this);
```
```
<!-- development flavor -->
<string name="pusher_app_key">XXXXXXXXXXXXX</string>
```
```
<!-- production flavor -->
<string name="pusher_app_key">YYYYYYYYYYYYY</string>
```
Much better, right?

**Comment by zmarkan** [comment]
I agree that not everyone uses Dagger there are similar, simpler ways to provide dependencies from a central place. 

However, I disagree with the standard way to init libraries by passing Context in the constructor. 
Most libraries that need Context need it for more than just a single resource value. 

I think not tying ourselves to any Android specifics allows more freedom to developers to use it however they wish. You can easily initialise Pusher by passing `getString(R.string.pusher_app_key)` to it. You can even create a little helper method that will do it for you!

Or, alternatively, if you have it in your `build.gradle` as a build variable you can access the value via the `BuildConfig` auto generated constant. 
Some people also specify a `Constants` file with these keys.
