### ISSUE TITLE
ETA for private- and presence- interests?

### ISSUE THREAD

**Issue by mautematico** [pusher/pusher-websocket-android#38]
¡Hola!

Your documentation states 

> [...] Note that the hyphen (-) is not a valid character in interest names. This character is reserved for the possibility in future of marking interest names with prefixes (such as private- or presence-).
https://pusher.com/docs/push_notifications/reference/client_api#v1-clients-client_id-interests-interest_name

Do you have an ETA for private- and presence- interests being available as an open beta?

**Comment by zmarkan** [comment]
Hi!

No, we don't have that planned currently. What people usually do to implement "private-ish" interests is by using hard to guess names instead. I hope that helps you.

**Comment by sirajsolutelabs** [comment]
Hi,

I want to subscribe private interest with same name as my websocket channel and event name like my websocket channel name is **private-userid** and my event name is **actual_event_name**. So when I try to use interest name as **private-userid_actual_event_name**, it gives me above error that hyphen is not allowed.

So what interest name is ideal for private and presence subscriptions?

**Comment by zmarkan** [comment]
There is no private and presence interests at this time, so what you can do is just use names that are hard to guess and/or random to get around it.
