### ISSUE TITLE
Missing Licence

### ISSUE THREAD

**Issue by chahine** [pusher/pusher-websocket-android#39]
### What is the issue?

Missing a Licence in this repo.

### Is it a crash report? Submit stack traces or anything that you think would help
No

### Any improvements you suggest

Please add a Licence file in the root folder of the repository. It would probably be the same as the one present in https://github.com/pusher/pusher-websocket-java

---- 

CC @pusher/mobile

**Comment by zmarkan** [comment]
Whoops, you're right! Adding it now. Thanks! 💯
