### ISSUE TITLE
Custom Firebase messaging service is not triggered

### ISSUE THREAD

**Issue by sirajsolutelabs** [pusher/pusher-websocket-android#42]
Hello,

I am using pusher android for sending push notification. For that, previously, I was using Pusher's Firebase messaging service. But unfortunately, It is only providing me the remotemessage when the user is foreground(pause state) and not in background(kill state). I want that onMessageReceived should trigger at the time of Push notification received(When notification is in system tray). But it was not coming. So Can you please tell me the reason why it is happening?

The other issue - So after using this, I thought about creating custom firebase service and used it. But it is not even triggered not in foreground not in background. Can you please help me with this?

The code I have used is as below:

AndroidManifest

```
<!-- Pusher's FCM listeners and services -->
        <service android:name=".pusher.CustomMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>

        <!--<service android:name="com.pusher.android.notifications.fcm.FCMMessagingService">-->
            <!--<intent-filter>-->
                <!--<action android:name="com.google.firebase.MESSAGING_EVENT"/>-->
            <!--</intent-filter>-->
        <!--</service>-->

        <!--<service android:name="com.pusher.android.notifications.fcm.FCMInstanceIDService">-->
            <!--<intent-filter>-->
                <!--<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>-->
            <!--</intent-filter>-->
        <!--</service>-->
```

I have commented the pusher messaging service, uncommenting instanceID also not working.

CustomMessagingService

```
public class CustomMessagingService extends FirebaseMessagingService {

    private static final String TAG = "CustomMessagingService";

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);

        Log.d(TAG, "onMessageReceived: called");

        if (remoteMessage.getData() != null) {
            Map<String, String> data = remoteMessage.getData();
            Log.d(TAG, "onMessageReceived: data " + data.size());
        } else {
            Log.d(TAG, "onMessageReceived: remoteMessage.GetData null");
        }
    }
}
```

**Comment by zmarkan** [comment]
What are you sending to the API? In particular - are you using the `notification` or `data` payload? 

According to the FCM spec the `notification` payload will default to the system notification tray if the app is not in the foreground, and the `data` payload will always trigger your callback.

You can find more info here: https://firebase.google.com/docs/cloud-messaging/concept-options

**Comment by sirajsolutelabs** [comment]
Thanks for the quick response.

Yes from backend server I am receiving notification payload and not data payload. I followed the pusher notification documentation where we have notification payload. https://pusher.com/docs/push_notifications/android/server_fcm#advanced-options

 So I will make the changes and look if I am able to resolve this issue with data payload. Thanks again

**Comment by sirajsolutelabs** [comment]
Hi,

I am following this documentation from Pusher to send custom data:
https://pusher.com/docs/push_notifications/android/server_fcm#custom-data

Like here, I am sending notification and data both payloads. Like notification includes title, body etc. and body includes my actual data.

So in this scenario, Why should my data is not coming in foreground?

**Comment by zmarkan** [comment]
Hmm - that seems odd, according to FCM docs it should work fine. I'll investigate 👍

**Comment by sirajsolutelabs** [comment]
Hello,

Thanks for the quick responses. As per the FCM docs, on using notification with data will work as:

**When in the background, apps receive the notification payload in the notification tray, and only handle the data payload when the user taps on the notification.
When in the foreground, your app receives a message object with both payloads available.**

It clearly says here that in background, we will receive data only when user taps on the notification. Without tapping I won't get it and my OnMessageReceived will not trigger

So if I want the data in onMessageReceived everytime, What's your take on this?

**Comment by kn100** [comment]
Closing due to age
