### ISSUE TITLE
pushnotificationRegistration

### ISSUE THREAD

**Issue by sagarmaiyad** [pusher/pusher-websocket-android#46]
### What is the issue?
i am registering pushnotification everytime application open like below.

    var regListener: PushNotificationRegistrationListener = object : PushNotificationRegistrationListener {
        override fun onSuccessfulRegistration() {
            Log.e("MainMenu","REGISTRATION SUCCESSFUL!!! YEEEEEHAWWWWW!")

        }

        override fun onFailedRegistration(statusCode: Int, response: String) {
            Log.e("MainMenu","REGISTRATION Failed ")
        }
    }
should i register everytime or not.?
... 

### Is it a crash report? Submit stack traces or anything that you think would help

...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by zmarkan** [comment]
That's correct, yes.
